# Generated by Django 5.1.1 on 2024-09-05 03:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('document', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('license_number', models.CharField(max_length=50)),
                ('date_of_birth', models.DateField(null=True)),
                ('years_of_experience', models.IntegerField(null=True)),
                ('gender', models.CharField(max_length=10)),
                ('status', models.BooleanField(default=True)),
                ('specialty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='medical.specialty')),
            ],
        ),
    ]
