# Generated by Django 5.1.1 on 2024-09-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='last_name',
            field=models.CharField(default='Sin apellido', max_length=100),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='document',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
